version: "1.0"
services:
  streamlit:
    container_name: streamlit_container
    image: python:3.10-slim
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
      - ./database:/database
    tty: true
    ports:
      - "8501:8501"
  database:
    container_name: database_container
    image: postgres:13.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ucvdata:/var/lib/postgresql/data
volumes:
  ucvdata: {}